//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimePartTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrameList
    {
        public int Id { get; set; }
        public string Item { get; set; }
        public string Blueprint { get; set; }
        public string Neuroptics { get; set; }
        public string Chassis { get; set; }
        public string Systems { get; set; }
    }
}
