//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimePartTracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrimesEntities : DbContext
    {
        public PrimesEntities()
            : base("name=PrimesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FrameList> FrameLists { get; set; }
        public virtual DbSet<MeleeList> MeleeLists { get; set; }
        public virtual DbSet<PrimaryList> PrimaryLists { get; set; }
    }
}
